# Generated by Django 3.0 on 2019-12-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freefeeds', '0004_auto_20191222_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='height',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='width',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments_disabled',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
